services:
  webapp:
    build:
      context: ./services/webapp
      dockerfile: Dockerfile.dev
    environment:
      - ENABLE_OTEL=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
    volumes:
      - ./services/webapp/app:/app/app
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - "16686:16686"
      - "4318:4318"
