FROM python:3.11-alpine3.21
RUN apk add --no-cache ca-certificates
USER root
RUN python -m pip install --upgrade pip "setuptools>=78.1.1" "wheel>=0.46.2"


WORKDIR /app


RUN addgroup --system app && adduser --system --ingroup app app


ENV HOME=/home/app
RUN mkdir -p /home/app/.cache/pip && chown -R app:app /home/app


ARG REQUIREMENTS_FILE=requirements-prod.txt


COPY ${REQUIREMENTS_FILE} /app/requirements.txt
RUN python -m pip install --upgrade pip "setuptools>=78.1.1" "wheel>=0.46.2" \


COPY --chown=app:app app ./app

USER app

EXPOSE 5000
CMD ["gunicorn", "-w", "2", "-b", "0.0.0.0:5000", "app.main:app"]

